apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: tenant
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tenant
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.14