apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: tenant
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tenant
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.3.14